package todoapp.app.services.demoeventsubscriber;

public enum DemoBehaviour {
    ACTIVITY_MENU_HIDE_ALL,
    ACTIVITY_MENU_HIDE_SESSION_LOGGER,
    ACTIVITY_MENU_HIDE_AUDITING,
    ACTIVITY_MENU_HIDE_COMMAND,
    ACTIVITY_MENU_HIDE_PUBLISHING,
    ANY_EXECUTE_ACCEPT,
    ANY_EXECUTE_VETO_WITH_RECOVERABLE_EXCEPTION,
    ANY_EXECUTE_VETO_WITH_NON_RECOVERABLE_EXCEPTION,
    ANY_EXECUTE_VETO_WITH_OTHER_EXCEPTION,
    UPDATE_COST_ACTION_HIDE,
    UPDATE_COST_ACTION_DISABLE,
    UPDATE_COST_ACTION_INVALIDATE,
    DESCRIPTION_PROPERTY_HIDE,
    DESCRIPTION_PROPERTY_DISABLE,
    DESCRIPTION_PROPERTY_INVALIDATE,
    DEPENDENCIES_COLLECTION_HIDE,
    // not implemented in Wicket viewer, but supported in wrapped objects
    DEPENDENCIES_COLLECTION_DISABLE,
    // not implemented in Wicket viewer, but supported in wrapped objects
    DEPENDENCIES_COLLECTION_INVALIDATE_ADD,
    DEPENDENCIES_COLLECTION_INVALIDATE_REMOVE,
    SIMILAR_TO_COLLECTION_HIDE
}
